steps:
  - name: gcr.io/cloud-builders/docker
    args: ['build', '-t', '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/benefit-settlement-rail:$COMMIT_SHA', '.']
  - name: gcr.io/cloud-builders/docker
    args: ['push', '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/benefit-settlement-rail:$COMMIT_SHA']
images:
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/benefit-settlement-rail:$COMMIT_SHA'
substitutions:
  _REGION: us-central1
  _REPOSITORY: cloud-run-source-deploy
options:
  logging: CLOUD_LOGGING_ONLY
