import test from 'node:test';
import assert from 'node:assert/strict';
import { DemoWorkflowService } from '../src/demo-workflow/service.ts';
import { DemoWorkflowStore } from '../src/demo-workflow/store.ts';
import { createMockProvider, demoRequirements } from '../src/demo-workflow/mockProvider.ts';
const now=Date.parse('2026-09-18T01:00:00Z');
function setup(scenario:'success'|'unavailable'='success'){const store=new DemoWorkflowStore();const service=new DemoWorkflowService(store,createMockProvider(scenario,()=>now),()=>now);return {store,service};}
test('audience starts empty; draft consent is only activated by actual DTMF',async()=>{
 const {store,service}=setup();const p=service.begin('presenter','bound-presenter','audience');assert.deepEqual(p.requirements,{});const {consent:ignored,...requirements}=demoRequirements(now);service.update('presenter',requirements,'실제 고객 조건');assert.equal(service.status('presenter').requirements.consent,undefined);
 service.begin('judge','bound-audience','audience');assert.deepEqual(service.status('judge').requirements,{});assert.throws(()=>service.begin('judge','bound-audience','standard'),/IDENTITY/);
 const draft=service.prepareSeed('presenter');assert.equal(store.read('presenter')!.requirements.consent,undefined);assert.equal(store.read('presenter')!.seed?.approvalRef,undefined);assert.match(draft.readback,/모의 기관 문의와 모의 신청/);assert.match(draft.readback,/일 번/);await assert.rejects(service.run('presenter'),/APPROVAL/);
 service.approve('presenter',draft.seedHash!,draft.nonce,'1');assert.deepEqual(service.status('presenter').requirements.consent,{contact:true,submit:true,callback:true});await service.run('presenter');const c=store.read('presenter')!;assert.equal(c.ev2?.pass,true);assert.equal(c.phase,'READY');const job=service.claimCallback('presenter').job!;assert.equal(job.experienceMode,'audience');assert.equal(job.nextOpportunity,undefined);service.answerCallback('presenter',job.id,'1');assert.equal(store.read('presenter')!.reservation,undefined);assert.equal(service.completeCallback('presenter',job.id,{answered:true,acknowledged:true,completed:true,receiptRef:'sdk:receipt'}).delivered,true);store.close();
});
test('fixed catalog does not manufacture region, quantity, allergy, deadline or item from Seed',async()=>{
 for(const patch of [{region:'부산 해운대구'},{quantity:2},{dietaryRestrictions:['땅콩 알레르기']},{neededBy:new Date(now+10000).toISOString()},{item:'의약품'}]){
  const {store,service}=setup();service.begin('judge','judge','audience');service.update('judge',{...demoRequirements(now),...patch},'실제 사용자 조건');const s=service.prepareSeed('judge');service.approve('judge',s.seedHash!,s.nonce,'1');await service.run('judge');const c=store.read('judge')!;assert.equal(c.receipt,undefined,JSON.stringify(patch));assert.equal(c.ev1?.pass,false);assert.doesNotMatch(c.callback!.message,/예약할까요/);store.close();
 }
});
test('meal aliases match fixed meal without altering unrelated requested items',async()=>{const {store,service}=setup();service.begin('j','j','audience');service.update('j',{...demoRequirements(now),item:'음식'},'음식이 필요해요');const d=service.prepareSeed('j');service.approve('j',d.seedHash!,d.nonce,'1');await service.run('j');assert.equal(store.read('j')!.ev2?.pass,true);assert.equal(store.read('j')!.plan?.terms.item,'한 끼 식사');store.close();});
test('explicit declined consent is not silently replaced and callback exit never schedules next call',async()=>{const {store,service}=setup('unavailable');service.begin('p','p','audience');service.update('p',demoRequirements(now),'조건');service.update('p',{consent:{contact:false,submit:false,callback:false}},'아니요 동의하지 않아요');assert.throws(()=>service.prepareSeed('p'),/CONSENT_DECLINED/);service.update('p',{consent:{contact:true,submit:true,callback:true},noMatchPreference:'offer_callback'},'조건 수정');const d=service.prepareSeed('p');service.approve('p',d.seedHash!,d.nonce,'1');await service.run('p');const job=service.claimCallback('p').job!;assert.equal(job.nextOpportunity,undefined);assert.doesNotMatch(job.message,/예약할까요/);service.answerCallback('p',job.id,'1');assert.equal(store.read('p')!.reservation,undefined);store.close();});
test('catalog has fixed 12-hour slots independent of Seeds and skips expired slots',async()=>{
 let clock=now;const provider=createMockProvider('success',()=>clock);const r=demoRequirements(now);const seed={version:1,hash:'test-seed',requirements:r};const task={id:'B:0',institutionId:'B',institutionName:'B',item:'한 끼 식사',priority:0};
 const first=await provider.inquire(task,seed,new AbortController().signal);assert.equal(first.kind,'available');if(first.kind!=='available')throw Error();assert.equal(first.terms.promisedBy,new Date(now+1800000).toISOString());
 clock=now+31*60000;const second=await provider.inquire(task,seed,new AbortController().signal);assert.equal(second.kind,'available');if(second.kind!=='available')throw Error();assert.equal(second.terms.promisedBy,new Date(now+3600000).toISOString());assert.notEqual(second.terms.promisedBy,seed.requirements.neededBy);
 clock=now+12*3600000;const expired=await provider.inquire(task,{...seed,requirements:{...r,neededBy:new Date(clock+3600000).toISOString()}},new AbortController().signal);assert.equal(expired.kind,'unavailable');
});
test('audience readback includes no-match scope and correct non-meal quantity unit',()=>{const {store,service}=setup();service.begin('j','j','audience');service.update('j',{...demoRequirements(now),item:'의약품',noMatchPreference:'offer_callback'},'의약품 필요');const d=service.prepareSeed('j');assert.match(d.readback,/의약품 한 개/);assert.match(d.readback,/다음 가능한 방법/);assert.match(d.readback,/추가 예약은 하지 않습니다/);service.approve('j',d.seedHash!,d.nonce,'2');service.update('j',{noMatchPreference:'stop'},'결과만 알려주세요');assert.match(service.prepareSeed('j').readback,/결과만 안내합니다/);store.close();});
