import test from 'node:test';
import assert from 'node:assert/strict';
import { once } from 'node:events';
import { mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { createCareApp } from '../../src/careApp.ts';

test('support network and protected multi-need requests share real HTTP storage', async t => {
  const token = 'coordination-test-operator-token-000000000000';
  const prior = process.env.CARE_OPERATOR_TOKEN;
  process.env.CARE_OPERATOR_TOKEN = token;
  const server = createCareApp();
  if (prior === undefined) delete process.env.CARE_OPERATOR_TOKEN; else process.env.CARE_OPERATOR_TOKEN = prior;
  server.listen(0, '127.0.0.1');
  await once(server, 'listening');
  t.after(() => server.close());
  const address = server.address(); assert.ok(address && typeof address !== 'string');
  const base = `http://127.0.0.1:${address.port}`;
  const headers = {authorization: `Bearer ${token}`, 'content-type':'application/json'};
  const programs = await fetch(base+'/api/support/programs');
  assert.equal(programs.status, 200);
  assert.equal((await programs.json()).programs.length, 4);
  assert.equal((await fetch(base+'/api/coordination/requests')).status,403);
  const created = await fetch(base+'/api/coordination/requests',{method:'POST',headers,body:JSON.stringify({
    citizenRef:'citizen-a', summary:'쌀은 있지만 조리가 어렵고 비누가 필요합니다',district:'마포구',
    constraints:['직접 방문 어려움'], needs:[{description:'조리된 식사',category:'식사'},{description:'비누',category:'생필품'}]
  })});
  assert.equal(created.status,201);
  const {request}=await created.json();
  assert.equal(request.needs.length,2);
  assert.equal(request.needs[0].description,'조리된 식사');
  const result=await fetch(base+`/api/coordination/requests/${request.id}`,{headers});
  assert.equal((await result.json()).request.id,request.id);
  const stopped=await fetch(base+`/api/coordination/requests/${request.id}/needs/${request.needs[1].id}/stop`,{method:'POST',headers,body:'{}'});
  assert.equal(stopped.status,200);
  const stopBody=await stopped.json();
  assert.equal(stopBody.request.needs[1].status,'stopped');
  assert.equal(stopBody.request.needs[0].status,'open');
  const invalid=await fetch(base+'/api/coordination/requests',{method:'POST',headers,body:JSON.stringify({needs:'bad'})});
  assert.equal(invalid.status,400);
  const invalidConsent=await fetch(base+`/api/coordination/requests/${request.id}/consent`,{method:'POST',headers,body:JSON.stringify({purpose:'문의',institutionIds:[],sharedFields:[],allowCoordination:'true'})});
  assert.equal(invalidConsent.status,400);
  const network=await fetch(base+'/api/support/institutions?programId=foodbank-market').then(r=>r.json());
  const institution=network.institutions[0];
  const post=async (suffix:string,value:unknown)=>fetch(base+`/api/coordination/requests/${request.id}/${suffix}`,{method:'POST',headers,body:JSON.stringify(value)});
  assert.equal((await post('consent',{purpose:'식사 지원 문의',institutionIds:[institution.id],sharedFields:['needs'],allowCoordination:false})).status,200);
  const prepared=await post('inquiries',{needId:request.needs[0].id,institutionId:institution.id,programId:'foodbank-market',contactPurpose:institution.contacts[0].purpose,questions:['식사 지원 절차는 무엇인가요?']});
  assert.equal(prepared.status,201);
  const inquiry=(await prepared.json()).inquiry;
  const started=await post(`inquiries/${inquiry.id}/attempts`,{idempotencyKey:'http-retry-first'});
  const attempt=(await started.json()).attempt;
  assert.equal((await post(`attempts/${attempt.id}/result`,{status:'no-answer'})).status,200);
  const retry=await post(`inquiries/${inquiry.id}/retry`,{});
  assert.equal(retry.status,200);
  assert.equal((await retry.json()).request.inquiries[0].status,'prepared');
});

test('coordination reuses configured care ledger and survives HTTP server restart',async t=>{
  const directory=mkdtempSync(join(tmpdir(),'coordination-http-'));
  t.after(()=>rmSync(directory,{recursive:true,force:true}));
  const previousPath=process.env.CARE_LEDGER_PATH, previousToken=process.env.CARE_OPERATOR_TOKEN;
  const token='http-persistence-operator-00000000000000';
  process.env.CARE_LEDGER_PATH=join(directory,'ledger.sqlite');
  process.env.CARE_OPERATOR_TOKEN=token;
  const first=createCareApp();
  first.listen(0,'127.0.0.1');await once(first,'listening');
  const address=first.address();assert.ok(address&&typeof address!=='string');
  const response=await fetch(`http://127.0.0.1:${address.port}/api/coordination/requests`,{method:'POST',headers:{authorization:`Bearer ${token}`,'content-type':'application/json'},body:JSON.stringify({citizenRef:'citizen-r',summary:'식사 지원',district:'마포구',constraints:[],needs:[{description:'식사',category:'식사'}]})});
  assert.equal(response.status,201);const saved=await response.json();
  await new Promise<void>(resolve=>first.close(()=>resolve()));
  const second=createCareApp();
  if(previousPath===undefined) delete process.env.CARE_LEDGER_PATH;else process.env.CARE_LEDGER_PATH=previousPath;
  if(previousToken===undefined) delete process.env.CARE_OPERATOR_TOKEN;else process.env.CARE_OPERATOR_TOKEN=previousToken;
  second.listen(0,'127.0.0.1');await once(second,'listening');t.after(()=>second.close());
  const secondAddress=second.address();assert.ok(secondAddress&&typeof secondAddress!=='string');
  const restored=await fetch(`http://127.0.0.1:${secondAddress.port}/api/coordination/requests/${saved.request.id}`,{headers:{authorization:`Bearer ${token}`}});
  assert.equal(restored.status,200);
  assert.equal((await restored.json()).request.summary,'식사 지원');
});

test('operator browser session protects mutations and never returns the access code', async t=>{
  const savedToken=process.env.CARE_OPERATOR_TOKEN, savedBase=process.env.PUBLIC_BASE_URL;
  const token='browser-session-access-code-0000000000000';
  process.env.CARE_OPERATOR_TOKEN=token;delete process.env.PUBLIC_BASE_URL;
  const server=createCareApp();
  if(savedToken===undefined)delete process.env.CARE_OPERATOR_TOKEN;else process.env.CARE_OPERATOR_TOKEN=savedToken;
  if(savedBase===undefined)delete process.env.PUBLIC_BASE_URL;else process.env.PUBLIC_BASE_URL=savedBase;
  server.listen(0,'127.0.0.1');await once(server,'listening');t.after(()=>server.close());
  const address=server.address();assert.ok(address&&typeof address!=='string');
  const base=`http://127.0.0.1:${address.port}`;
  const login=await fetch(base+'/api/coordination/session',{method:'POST',headers:{'content-type':'application/json',origin:base},body:JSON.stringify({accessCode:token})});
  assert.equal(login.status,200);
  assert.deepEqual(await login.json(),{authenticated:true});
  const setCookie=login.headers.get('set-cookie')!;assert.match(setCookie,/HttpOnly/);assert.ok(!setCookie.includes(token));
  const cookie=setCookie.split(';')[0]!;
  assert.equal((await fetch(base+'/api/coordination/requests',{headers:{cookie}})).status,200);
  const body=JSON.stringify({citizenRef:'browser-request',summary:'식사',district:'성동구',constraints:[],needs:[{description:'식사',category:'식사'}]});
  const post=(origin:string)=>fetch(base+'/api/coordination/requests',{method:'POST',headers:{cookie,origin,'content-type':'application/json'},body});
  assert.equal((await post('https://unrelated.example')).status,403);
  assert.equal((await post(base)).status,201);
  assert.equal((await fetch(base+'/api/coordination/session',{method:'DELETE',headers:{cookie,origin:base}})).status,200);
  assert.equal((await fetch(base+'/api/coordination/requests',{headers:{cookie}})).status,403);
});
